// ══════════════════════════════════════════════════════════════════
// CourtDraw — Professional Tactics Library
// Coordinate system: 0–1000 (x) × 0–600 (y)
// Tokens use normalized 0–1 fractions: pct:[px, py]
// ══════════════════════════════════════════════════════════════════

window.TACTICS_LIBRARY = [

  // ─────────────────────────────────────────────
  // TENNIS (6 tactics)
  // Court: x=70–930, y=151–449
  // Net at x=500; service lines y=192 and y=408
  // Center service line x=268 (left) x=732 (right)
  // ─────────────────────────────────────────────
  {
    id: 'tennis_serve_volley',
    sport: 'Tennis',
    courtId: 'tennis_singles',
    name: 'Serve & Volley',
    category: 'Offense',
    tier: 'free',
    description: 'Server charges net after a wide serve to cut off angles and finish at the net.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[140, 408], [450, 230]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[140, 408], [320, 340]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[320, 340], [270, 290]] },
      { type: 'dashed-arrow', color: '#ef4444', lineWidth: 3, points: [[860, 300], [420, 220]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.14, 0.68] },
      { team: 'red',  label: '1', pct: [0.86, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'tennis_baseline_rally',
    sport: 'Tennis',
    courtId: 'tennis_singles',
    name: 'Baseline Cross-Court Rally',
    category: 'Offense',
    tier: 'free',
    description: 'Consistent cross-court groundstrokes to open the court for a down-the-line winner.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[180, 420], [800, 170]] },
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[820, 170], [200, 420]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[200, 420], [870, 175]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[200, 420], [800, 420]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.18, 0.72] },
      { team: 'red',  label: '1', pct: [0.82, 0.28] },
    ],
    phases: null,
  },
  {
    id: 'tennis_net_approach',
    sport: 'Tennis',
    courtId: 'tennis_singles',
    name: 'Net Approach (Short Ball)',
    category: 'Offense',
    tier: 'pro',
    description: 'Capitalize on a short ball by driving an approach shot and closing the net.',
    objects: [
      { type: 'circle', color: '#fbbf24', lineWidth: 3, cx: 420, cy: 300, r: 30 },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[140, 400], [420, 300]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[420, 300], [350, 240]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[350, 240], [250, 270]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.14, 0.67] },
      { team: 'red',  label: '1', pct: [0.86, 0.40] },
    ],
    phases: null,
  },
  {
    id: 'tennis_return_of_serve',
    sport: 'Tennis',
    courtId: 'tennis_singles',
    name: 'Return of Serve — Chip & Charge',
    category: 'Offense',
    tier: 'pro',
    description: 'Chip a low return at the server\'s feet and rush the net to exploit the weak volley.',
    objects: [
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[860, 192], [580, 230]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[580, 230], [700, 340]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[580, 230], [640, 290]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[640, 290], [550, 265]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.60, 0.38] },
      { team: 'red',  label: '1', pct: [0.86, 0.32] },
    ],
    phases: null,
  },
  {
    id: 'tennis_lob_defense',
    sport: 'Tennis',
    courtId: 'tennis_singles',
    name: 'Lob Defense — Overhead',
    category: 'Defense',
    tier: 'pro',
    description: 'Counter a deep lob with a smash overhead when near the net, or retreat and reset.',
    objects: [
      { type: 'dashed-arrow', color: '#ef4444', lineWidth: 3, points: [[700, 420], [300, 170]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[300, 270], [300, 175]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[300, 175], [750, 380]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[300, 270], [170, 370]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.30, 0.45] },
      { team: 'red',  label: '1', pct: [0.70, 0.70] },
    ],
    phases: null,
  },
  {
    id: 'tennis_topspin_rally',
    sport: 'Tennis',
    courtId: 'tennis_singles',
    name: 'Heavy Topspin — Corner Attack',
    category: 'Offense',
    tier: 'pro',
    description: 'Use heavy topspin to push the opponent off the court and finish down the line.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[160, 400], [820, 160]] },
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[820, 160], [750, 420]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[200, 420], [870, 420]] },
      { type: 'circle', color: '#a3e635', lineWidth: 3, cx: 870, cy: 420, r: 28 },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.16, 0.67] },
      { team: 'red',  label: '1', pct: [0.82, 0.27] },
    ],
    phases: null,
  },

  // ─────────────────────────────────────────────
  // PADEL (6 tactics)
  // Court: x=70–930, y=85–515; net x=500
  // Service boxes separated at x=371 and x=629
  // ─────────────────────────────────────────────
  {
    id: 'padel_lob',
    sport: 'Padel',
    courtId: 'padel',
    name: 'Defensive Lob',
    category: 'Defense',
    tier: 'free',
    description: 'Lob the ball over the net players to force them back from the net position.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[160, 440], [500, 120]] },
      { type: 'dashed-arrow', color: '#ef4444', lineWidth: 3, points: [[580, 180], [580, 420]] },
      { type: 'dashed-arrow', color: '#ef4444', lineWidth: 3, points: [[800, 180], [800, 420]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.14, 0.73] },
      { team: 'blue', label: '2', pct: [0.30, 0.73] },
      { team: 'red',  label: '1', pct: [0.60, 0.30] },
      { team: 'red',  label: '2', pct: [0.82, 0.30] },
    ],
    phases: null,
  },
  {
    id: 'padel_bandeja',
    sport: 'Padel',
    courtId: 'padel',
    name: 'Bandeja (Overhead Slice)',
    category: 'Offense',
    tier: 'free',
    description: 'Defensive overhead to maintain net position while placing the ball in a difficult spot.',
    objects: [
      { type: 'dashed-arrow', color: '#ef4444', lineWidth: 3, points: [[160, 440], [600, 130]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[580, 200], [860, 450]] },
      { type: 'circle', color: '#fbbf24', lineWidth: 3, cx: 580, cy: 200, r: 35 },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.56, 0.25] },
      { team: 'blue', label: '2', pct: [0.78, 0.25] },
      { team: 'red',  label: '1', pct: [0.14, 0.73] },
      { team: 'red',  label: '2', pct: [0.30, 0.73] },
    ],
    phases: null,
  },
  {
    id: 'padel_serve_pattern',
    sport: 'Padel',
    courtId: 'padel',
    name: 'Serve to Body + Net Rush',
    category: 'Serve',
    tier: 'pro',
    description: 'Serve to the opponent\'s body, then rush the net with your partner for the put-away.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[140, 300], [750, 300]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[140, 300], [320, 220]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[300, 180], [420, 220]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.14, 0.50] },
      { team: 'blue', label: '2', pct: [0.30, 0.30] },
      { team: 'red',  label: '1', pct: [0.76, 0.50] },
      { team: 'red',  label: '2', pct: [0.82, 0.30] },
    ],
    phases: null,
  },
  {
    id: 'padel_net_domination',
    sport: 'Padel',
    courtId: 'padel',
    name: 'Net Domination',
    category: 'Offense',
    tier: 'pro',
    description: 'Both players hold the net and use volleys to keep pressure until a smash opportunity.',
    objects: [
      { type: 'rect', color: '#60a5fa', lineWidth: 2, x: 520, y: 150, w: 360, h: 300 },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[580, 250], [200, 420]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[820, 250], [200, 180]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.60, 0.30] },
      { team: 'blue', label: '2', pct: [0.82, 0.30] },
      { team: 'red',  label: '1', pct: [0.14, 0.70] },
      { team: 'red',  label: '2', pct: [0.30, 0.70] },
    ],
    phases: null,
  },
  {
    id: 'padel_wall_play',
    sport: 'Padel',
    courtId: 'padel',
    name: 'Back Wall Play',
    category: 'Defense',
    tier: 'pro',
    description: 'Use the back glass wall to keep the ball in play and redirect the attack.',
    objects: [
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[600, 200], [180, 470]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[180, 470], [90, 400]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[90, 400], [700, 200]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.14, 0.73] },
      { team: 'blue', label: '2', pct: [0.30, 0.73] },
      { team: 'red',  label: '1', pct: [0.60, 0.25] },
      { team: 'red',  label: '2', pct: [0.82, 0.25] },
    ],
    phases: null,
  },
  {
    id: 'padel_smash_counter',
    sport: 'Padel',
    courtId: 'padel',
    name: 'Smash Counter — Byke',
    category: 'Defense',
    tier: 'pro',
    description: 'Absorb a smash off the back wall and launch a counter-attack lob.',
    objects: [
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[600, 200], [200, 460]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[200, 460], [90, 350]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[90, 350], [90, 150]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[90, 150], [700, 110]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.14, 0.73] },
      { team: 'blue', label: '2', pct: [0.30, 0.73] },
      { team: 'red',  label: '1', pct: [0.60, 0.25] },
      { team: 'red',  label: '2', pct: [0.82, 0.25] },
    ],
    phases: null,
  },

  // ─────────────────────────────────────────────
  // PICKLEBALL (6 tactics)
  // Court: x=70–930, y=104–496; net x=500
  // Kitchen zones x=363–637 (center region)
  // ─────────────────────────────────────────────
  {
    id: 'pickleball_dink_rally',
    sport: 'Pickleball',
    courtId: 'pickleball',
    name: 'Dink Rally',
    category: 'Offense',
    tier: 'free',
    description: 'Patient cross-court dinking to wait for an error or a pop-up to attack.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[450, 420], [540, 180]] },
      { type: 'arrow', color: '#ef4444', lineWidth: 3, points: [[540, 180], [460, 420]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[460, 420], [550, 175]] },
      { type: 'circle', color: '#a3e635', lineWidth: 2, cx: 500, cy: 300, r: 18 },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.43, 0.70] },
      { team: 'blue', label: '2', pct: [0.65, 0.70] },
      { team: 'red',  label: '1', pct: [0.43, 0.30] },
      { team: 'red',  label: '2', pct: [0.65, 0.30] },
    ],
    phases: null,
  },
  {
    id: 'pickleball_third_shot_drop',
    sport: 'Pickleball',
    courtId: 'pickleball',
    name: 'Third Shot Drop',
    category: 'Offense',
    tier: 'free',
    description: 'Drop the third shot softly into the kitchen to neutralize the net players\' advantage.',
    objects: [
      { type: 'arrow', color: '#ef4444', lineWidth: 3, points: [[860, 300], [140, 400]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[140, 400], [430, 300]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[140, 400], [380, 300]] },
      { type: 'rect', color: '#a3e635', lineWidth: 2, x: 363, y: 104, w: 274, h: 100 },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.14, 0.67] },
      { team: 'blue', label: '2', pct: [0.28, 0.67] },
      { team: 'red',  label: '1', pct: [0.43, 0.28] },
      { team: 'red',  label: '2', pct: [0.65, 0.28] },
    ],
    phases: null,
  },
  {
    id: 'pickleball_kitchen_control',
    sport: 'Pickleball',
    courtId: 'pickleball',
    name: 'Kitchen Line Control',
    category: 'Offense',
    tier: 'pro',
    description: 'Both partners dominate the kitchen line forcing opponents into unattackable dinks.',
    objects: [
      { type: 'rect', color: '#60a5fa', lineWidth: 3, x: 520, y: 280, w: 370, h: 50 },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[580, 380], [580, 310]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[820, 380], [820, 310]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.57, 0.52] },
      { team: 'blue', label: '2', pct: [0.82, 0.52] },
      { team: 'red',  label: '1', pct: [0.14, 0.67] },
      { team: 'red',  label: '2', pct: [0.28, 0.67] },
    ],
    phases: null,
  },
  {
    id: 'pickleball_lob_defense',
    sport: 'Pickleball',
    courtId: 'pickleball',
    name: 'Lob Defense — Reset',
    category: 'Defense',
    tier: 'pro',
    description: 'When lobbed, one partner retreats while the other holds; reset with a soft drop.',
    objects: [
      { type: 'dashed-arrow', color: '#ef4444', lineWidth: 3, points: [[460, 350], [150, 130]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[580, 320], [580, 480]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[150, 130], [450, 300]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.46, 0.55] },
      { team: 'blue', label: '2', pct: [0.60, 0.52] },
      { team: 'red',  label: '1', pct: [0.43, 0.28] },
      { team: 'red',  label: '2', pct: [0.65, 0.28] },
    ],
    phases: null,
  },
  {
    id: 'pickleball_stacking',
    sport: 'Pickleball',
    courtId: 'pickleball',
    name: 'Stacking Formation',
    category: 'Offense',
    tier: 'pro',
    description: 'Stack both players on the same side to keep the stronger player on the forehand.',
    objects: [
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[140, 300], [580, 300]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[580, 300], [820, 200]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[140, 350], [390, 300]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.14, 0.50] },
      { team: 'blue', label: '2', pct: [0.14, 0.60] },
      { team: 'red',  label: '1', pct: [0.57, 0.52] },
      { team: 'red',  label: '2', pct: [0.82, 0.52] },
    ],
    phases: null,
  },
  {
    id: 'pickleball_transition_zone',
    sport: 'Pickleball',
    courtId: 'pickleball',
    name: 'Transition Zone Attack',
    category: 'Offense',
    tier: 'pro',
    description: 'Attack the ball in the no-man\'s land to put opponents on the defensive.',
    objects: [
      { type: 'rect', color: '#fbbf24', lineWidth: 2, x: 363, y: 280, w: 274, h: 140 },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[500, 390], [700, 200]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[500, 350], [300, 200]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.50, 0.67] },
      { team: 'blue', label: '2', pct: [0.70, 0.67] },
      { team: 'red',  label: '1', pct: [0.43, 0.28] },
      { team: 'red',  label: '2', pct: [0.65, 0.28] },
    ],
    phases: null,
  },

  // ─────────────────────────────────────────────
  // FOOTBALL / SOCCER (8 tactics)
  // Court: x=130–870, y=60–540
  // Penalty box left x=130–260 y=184–416
  // Penalty spot left (196,300); center circle r=58
  // ─────────────────────────────────────────────
  {
    id: 'football_tiki_taka',
    sport: 'Football',
    courtId: 'football_full',
    name: 'Tiki-Taka Possession',
    category: 'Offense',
    tier: 'free',
    description: 'Short passing triangles in midfield to retain possession and create space.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[250, 300], [380, 240]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[380, 240], [500, 280]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[500, 280], [620, 220]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[620, 220], [500, 280]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[380, 240], [500, 180]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[500, 280], [500, 180]] },
    ],
    tokens: [
      { team: 'blue', label: '6', pct: [0.25, 0.50] },
      { team: 'blue', label: '8', pct: [0.38, 0.40] },
      { team: 'blue', label: '10', pct: [0.50, 0.47] },
      { team: 'blue', label: '7', pct: [0.64, 0.37] },
      { team: 'blue', label: '9', pct: [0.50, 0.30] },
      { team: 'red',  label: '5', pct: [0.55, 0.50] },
      { team: 'red',  label: '6', pct: [0.45, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'football_high_press',
    sport: 'Football',
    courtId: 'football_full',
    name: 'High Press (Gegenpressing)',
    category: 'Defense',
    tier: 'free',
    description: 'Immediately press the ball after losing possession to win it back in a dangerous area.',
    objects: [
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[760, 300], [680, 340]] },
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[680, 200], [680, 280]] },
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[720, 220], [700, 300]] },
      { type: 'circle', color: '#ef4444', lineWidth: 3, cx: 680, cy: 310, r: 60 },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[680, 340], [600, 340]] },
    ],
    tokens: [
      { team: 'blue', label: '9', pct: [0.76, 0.50] },
      { team: 'blue', label: '10', pct: [0.68, 0.33] },
      { team: 'blue', label: '8', pct: [0.72, 0.37] },
      { team: 'red',  label: '4', pct: [0.68, 0.57] },
      { team: 'red',  label: '5', pct: [0.60, 0.50] },
      { team: 'red',  label: '2', pct: [0.72, 0.43] },
    ],
    phases: null,
  },
  {
    id: 'football_counter_attack',
    sport: 'Football',
    courtId: 'football_full',
    name: 'Counter Attack',
    category: 'Offense',
    tier: 'pro',
    description: 'Win the ball deep and quickly transition into attack with direct passes.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[260, 300], [480, 260]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[480, 260], [700, 200]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[260, 350], [540, 400]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[540, 400], [730, 380]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[700, 200], [760, 270]] },
    ],
    tokens: [
      { team: 'blue', label: '6', pct: [0.26, 0.50] },
      { team: 'blue', label: '9', pct: [0.70, 0.33] },
      { team: 'blue', label: '11', pct: [0.26, 0.58] },
      { team: 'blue', label: '7', pct: [0.75, 0.45] },
      { team: 'red',  label: '4', pct: [0.50, 0.50] },
      { team: 'red',  label: '5', pct: [0.50, 0.40] },
    ],
    phases: null,
  },
  {
    id: 'football_corner_kick',
    sport: 'Football',
    courtId: 'football_full',
    name: 'Corner Kick — Near Post Flick',
    category: 'Set Pieces',
    tier: 'pro',
    description: 'Deliver to the near post for a flick-on to a runner attacking the far post.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[870, 540], [780, 300]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[780, 300], [700, 260]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[700, 260], [650, 310]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[700, 400], [710, 290]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[720, 420], [760, 340]] },
    ],
    tokens: [
      { team: 'blue', label: '9', pct: [0.78, 0.50] },
      { team: 'blue', label: '10', pct: [0.70, 0.43] },
      { team: 'blue', label: '6', pct: [0.70, 0.67] },
      { team: 'blue', label: '3', pct: [0.72, 0.70] },
      { team: 'red',  label: '4', pct: [0.75, 0.48] },
      { team: 'red',  label: '5', pct: [0.73, 0.55] },
    ],
    phases: null,
  },
  {
    id: 'football_free_kick',
    sport: 'Football',
    courtId: 'football_full',
    name: 'Free Kick — Wall & Far Post',
    category: 'Set Pieces',
    tier: 'pro',
    description: 'Strike over the wall or curl the ball around into the far corner.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[620, 230], [800, 200]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[620, 230], [800, 300]] },
      { type: 'rect', color: '#ef4444', lineWidth: 3, x: 660, y: 220, w: 50, h: 80 },
      { type: 'circle', color: '#fbbf24', lineWidth: 3, cx: 800, cy: 250, r: 50 },
    ],
    tokens: [
      { team: 'blue', label: '7', pct: [0.62, 0.38] },
      { team: 'blue', label: '9', pct: [0.80, 0.33] },
      { team: 'blue', label: '10', pct: [0.80, 0.50] },
      { team: 'red',  label: '4', pct: [0.68, 0.37] },
      { team: 'red',  label: '5', pct: [0.68, 0.47] },
      { team: 'red',  label: '6', pct: [0.68, 0.57] },
    ],
    phases: null,
  },
  {
    id: 'football_433_attack',
    sport: 'Football',
    courtId: 'football_full',
    name: '4-3-3 Wide Attack',
    category: 'Offense',
    tier: 'pro',
    description: 'Overlap from full-back with a wide winger to deliver a cross into the box.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[560, 130], [750, 180]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[560, 130], [720, 300]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[480, 180], [600, 180]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[750, 200], [800, 280]] },
    ],
    tokens: [
      { team: 'blue', label: '11', pct: [0.56, 0.22] },
      { team: 'blue', label: '3', pct: [0.48, 0.30] },
      { team: 'blue', label: '9', pct: [0.80, 0.50] },
      { team: 'blue', label: '10', pct: [0.64, 0.40] },
      { team: 'red',  label: '2', pct: [0.72, 0.27] },
      { team: 'red',  label: '4', pct: [0.76, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'football_low_block',
    sport: 'Football',
    courtId: 'football_full',
    name: 'Low Block Defense',
    category: 'Defense',
    tier: 'pro',
    description: 'Compact deep defensive block with two disciplined lines of four.',
    objects: [
      { type: 'rect', color: '#60a5fa', lineWidth: 2, x: 130, y: 240, w: 220, h: 120 },
      { type: 'line', color: '#60a5fa', lineWidth: 3, points: [[130, 300], [360, 300]] },
      { type: 'line', color: '#fbbf24', lineWidth: 3, points: [[130, 350], [360, 350]] },
    ],
    tokens: [
      { team: 'blue', label: '2', pct: [0.20, 0.40] },
      { team: 'blue', label: '5', pct: [0.27, 0.50] },
      { team: 'blue', label: '4', pct: [0.33, 0.50] },
      { team: 'blue', label: '3', pct: [0.20, 0.60] },
      { team: 'blue', label: '7', pct: [0.25, 0.35] },
      { team: 'blue', label: '8', pct: [0.30, 0.55] },
      { team: 'red',  label: '9', pct: [0.50, 0.50] },
      { team: 'red',  label: '10', pct: [0.50, 0.40] },
    ],
    phases: null,
  },
  {
    id: 'football_throw_in',
    sport: 'Football',
    courtId: 'football_full',
    name: 'Throw-In Combination',
    category: 'Set Pieces',
    tier: 'pro',
    description: 'Quick combination play from a throw-in to maintain possession and create space.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[870, 400], [780, 370]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[780, 370], [820, 290]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[820, 290], [720, 260]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[780, 380], [760, 320]] },
    ],
    tokens: [
      { team: 'blue', label: '3', pct: [0.87, 0.67] },
      { team: 'blue', label: '11', pct: [0.78, 0.62] },
      { team: 'blue', label: '8', pct: [0.82, 0.48] },
      { team: 'blue', label: '7', pct: [0.72, 0.43] },
      { team: 'red',  label: '2', pct: [0.80, 0.55] },
    ],
    phases: null,
  },

  // ─────────────────────────────────────────────
  // BASKETBALL (8 tactics)
  // Court: x=70–930, y=50–550
  // Paint left x=70–248 y=184–416; basket left (140,300)
  // Paint right x=752–930 y=184–416; basket right (860,300)
  // ─────────────────────────────────────────────
  {
    id: 'basketball_pick_roll',
    sport: 'Basketball',
    courtId: 'basketball_full',
    name: 'Pick & Roll',
    category: 'Offense',
    tier: 'free',
    description: 'PG uses the center\'s screen to drive, then C rolls to the basket for the lob.',
    objects: [
      { type: 'circle', color: '#fbbf24', lineWidth: 4, cx: 380, cy: 280, r: 36 },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[270, 300], [420, 260]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 4, points: [[380, 315], [230, 300]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[250, 220], [350, 230]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[250, 370], [350, 360]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.27, 0.50] },
      { team: 'blue', label: '5', pct: [0.38, 0.47] },
      { team: 'blue', label: '3', pct: [0.25, 0.37] },
      { team: 'blue', label: '2', pct: [0.25, 0.62] },
      { team: 'blue', label: '4', pct: [0.43, 0.35] },
      { team: 'red',  label: '1', pct: [0.32, 0.50] },
      { team: 'red',  label: '5', pct: [0.44, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'basketball_motion_offense',
    sport: 'Basketball',
    courtId: 'basketball_full',
    name: 'Five-Out Motion Offense',
    category: 'Offense',
    tier: 'free',
    description: 'All five players spread the floor; continuous cutting and passing creates openings.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[340, 200], [450, 250]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[450, 250], [350, 350]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[350, 350], [220, 300]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[250, 200], [340, 200]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.35, 0.33] },
      { team: 'blue', label: '2', pct: [0.25, 0.33] },
      { team: 'blue', label: '3', pct: [0.45, 0.25] },
      { team: 'blue', label: '4', pct: [0.25, 0.67] },
      { team: 'blue', label: '5', pct: [0.45, 0.67] },
      { team: 'red',  label: '1', pct: [0.38, 0.42] },
      { team: 'red',  label: '5', pct: [0.47, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'basketball_zone_23',
    sport: 'Basketball',
    courtId: 'basketball_full',
    name: '2-3 Zone Defense',
    category: 'Defense',
    tier: 'pro',
    description: 'Two defenders up top, three along the baseline to protect the paint and force perimeter shots.',
    objects: [
      { type: 'rect', color: '#ef4444', lineWidth: 2, x: 70, y: 184, w: 178, h: 232 },
      { type: 'arc', color: '#ef4444', lineWidth: 2, points: [[140, 184], [248, 184], [140, 300]] },
      { type: 'line', color: '#60a5fa', lineWidth: 3, points: [[200, 230], [420, 180]] },
      { type: 'line', color: '#60a5fa', lineWidth: 3, points: [[200, 370], [420, 420]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.29, 0.33] },
      { team: 'blue', label: '2', pct: [0.29, 0.67] },
      { team: 'blue', label: '3', pct: [0.18, 0.50] },
      { team: 'blue', label: '4', pct: [0.17, 0.35] },
      { team: 'blue', label: '5', pct: [0.17, 0.65] },
      { team: 'red',  label: '1', pct: [0.38, 0.33] },
      { team: 'red',  label: '3', pct: [0.38, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'basketball_fast_break',
    sport: 'Basketball',
    courtId: 'basketball_full',
    name: 'Fast Break — 3-on-2',
    category: 'Offense',
    tier: 'pro',
    description: 'Push in transition; ball-handler attacks the paint to draw defenders, then kicks out.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[250, 300], [580, 300]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[250, 220], [580, 220]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[250, 380], [580, 380]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[580, 300], [780, 300]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[580, 300], [780, 220]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.25, 0.50] },
      { team: 'blue', label: '2', pct: [0.25, 0.37] },
      { team: 'blue', label: '3', pct: [0.25, 0.63] },
      { team: 'red',  label: '4', pct: [0.65, 0.43] },
      { team: 'red',  label: '5', pct: [0.65, 0.57] },
    ],
    phases: null,
  },
  {
    id: 'basketball_isolation',
    sport: 'Basketball',
    courtId: 'basketball_full',
    name: 'Isolation Play',
    category: 'Offense',
    tier: 'pro',
    description: 'Clear one side for the best scorer to go one-on-one against their defender.',
    objects: [
      { type: 'arrow', color: '#fbbf24', lineWidth: 3, points: [[380, 300], [200, 300]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 3, points: [[350, 230], [200, 180]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 3, points: [[350, 370], [200, 420]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[420, 300], [300, 300]] },
      { type: 'circle', color: '#a3e635', lineWidth: 3, cx: 260, cy: 300, r: 50 },
    ],
    tokens: [
      { team: 'blue', label: '3', pct: [0.42, 0.50] },
      { team: 'blue', label: '1', pct: [0.38, 0.38] },
      { team: 'blue', label: '2', pct: [0.35, 0.62] },
      { team: 'blue', label: '4', pct: [0.22, 0.30] },
      { team: 'blue', label: '5', pct: [0.22, 0.70] },
      { team: 'red',  label: '3', pct: [0.45, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'basketball_box_out',
    sport: 'Basketball',
    courtId: 'basketball_full',
    name: 'Box Out — Defensive Rebound',
    category: 'Defense',
    tier: 'pro',
    description: 'Each defender pins their opponent from the basket on a shot attempt.',
    objects: [
      { type: 'circle', color: '#fbbf24', lineWidth: 3, cx: 180, cy: 300, r: 80 },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[180, 220], [160, 250]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[250, 280], [230, 270]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[180, 380], [160, 350]] },
    ],
    tokens: [
      { team: 'blue', label: '4', pct: [0.18, 0.37] },
      { team: 'blue', label: '5', pct: [0.25, 0.47] },
      { team: 'blue', label: '3', pct: [0.18, 0.63] },
      { team: 'red',  label: '4', pct: [0.20, 0.32] },
      { team: 'red',  label: '5', pct: [0.28, 0.50] },
      { team: 'red',  label: '3', pct: [0.20, 0.68] },
    ],
    phases: null,
  },
  {
    id: 'basketball_inbound',
    sport: 'Basketball',
    courtId: 'basketball_full',
    name: 'Sideline Inbound — Stack Play',
    category: 'Set Pieces',
    tier: 'pro',
    description: 'Stack play from a sideline inbound to free a shooter off a flare screen.',
    objects: [
      { type: 'circle', color: '#fbbf24', lineWidth: 3, cx: 350, cy: 300, r: 28 },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[290, 550], [350, 300]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[370, 300], [250, 220]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[350, 300], [200, 300]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.29, 0.92] },
      { team: 'blue', label: '2', pct: [0.35, 0.50] },
      { team: 'blue', label: '3', pct: [0.25, 0.37] },
      { team: 'blue', label: '5', pct: [0.40, 0.50] },
      { team: 'red',  label: '2', pct: [0.38, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'basketball_triangle',
    sport: 'Basketball',
    courtId: 'basketball_full',
    name: 'Triangle Offense',
    category: 'Offense',
    tier: 'pro',
    description: 'Post, wing, and corner form a triangle; reads create open shots or drives.',
    objects: [
      { type: 'line', color: '#fbbf24', lineWidth: 2, points: [[200, 300], [350, 180], [350, 420], [200, 300]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[350, 180], [400, 250]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[400, 250], [220, 300]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[350, 420], [400, 360]] },
    ],
    tokens: [
      { team: 'blue', label: '5', pct: [0.20, 0.50] },
      { team: 'blue', label: '3', pct: [0.35, 0.30] },
      { team: 'blue', label: '4', pct: [0.35, 0.70] },
      { team: 'blue', label: '1', pct: [0.40, 0.42] },
      { team: 'blue', label: '2', pct: [0.40, 0.60] },
      { team: 'red',  label: '5', pct: [0.23, 0.50] },
      { team: 'red',  label: '3', pct: [0.38, 0.33] },
    ],
    phases: null,
  },

  // ─────────────────────────────────────────────
  // VOLLEYBALL (6 tactics)
  // Court: x=70–930, y=130–470
  // Net at x=500; attack lines x=303 and x=697
  // ─────────────────────────────────────────────
  {
    id: 'volleyball_serve_receive',
    sport: 'Volleyball',
    courtId: 'volleyball',
    name: 'W-Formation Serve Receive',
    category: 'Defense',
    tier: 'free',
    description: 'W-formation to cover all serve zones; libero takes the back court.',
    objects: [
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[820, 300], [450, 400]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[450, 400], [300, 280]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[300, 280], [300, 200]] },
    ],
    tokens: [
      { team: 'blue', label: '6', pct: [0.25, 0.73] },
      { team: 'blue', label: '5', pct: [0.15, 0.60] },
      { team: 'blue', label: '1', pct: [0.35, 0.60] },
      { team: 'blue', label: '4', pct: [0.15, 0.47] },
      { team: 'blue', label: '3', pct: [0.25, 0.40] },
      { team: 'blue', label: '2', pct: [0.35, 0.47] },
      { team: 'red',  label: '1', pct: [0.82, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'volleyball_quick_set',
    sport: 'Volleyball',
    courtId: 'volleyball',
    name: 'Quick Set — Middle Attack',
    category: 'Offense',
    tier: 'free',
    description: 'Setter delivers a quick low set to the middle blocker for a fast attack.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[260, 300], [320, 280]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[320, 280], [480, 270]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[480, 220], [480, 270]] },
    ],
    tokens: [
      { team: 'blue', label: '6', pct: [0.26, 0.55] },
      { team: 'blue', label: '2', pct: [0.32, 0.47] },
      { team: 'blue', label: '3', pct: [0.48, 0.40] },
      { team: 'blue', label: '4', pct: [0.16, 0.43] },
      { team: 'blue', label: '5', pct: [0.16, 0.55] },
      { team: 'red',  label: '2', pct: [0.65, 0.47] },
      { team: 'red',  label: '3', pct: [0.75, 0.47] },
    ],
    phases: null,
  },
  {
    id: 'volleyball_libero_rotation',
    sport: 'Volleyball',
    courtId: 'volleyball',
    name: 'Libero Rotation',
    category: 'Defense',
    tier: 'pro',
    description: 'Libero replaces middle blocker in back row for superior defensive coverage.',
    objects: [
      { type: 'dashed-arrow', color: '#a3e635', lineWidth: 3, points: [[250, 380], [250, 440]] },
      { type: 'dashed-arrow', color: '#a3e635', lineWidth: 3, points: [[280, 440], [280, 380]] },
      { type: 'circle', color: '#a3e635', lineWidth: 3, cx: 250, cy: 440, r: 28 },
    ],
    tokens: [
      { team: 'blue', label: '6', pct: [0.25, 0.73] },
      { team: 'blue', label: '5', pct: [0.15, 0.60] },
      { team: 'blue', label: 'L', pct: [0.28, 0.73] },
      { team: 'blue', label: '4', pct: [0.15, 0.47] },
      { team: 'blue', label: '3', pct: [0.25, 0.40] },
      { team: 'blue', label: '2', pct: [0.35, 0.47] },
    ],
    phases: null,
  },
  {
    id: 'volleyball_pipe_attack',
    sport: 'Volleyball',
    courtId: 'volleyball',
    name: 'Pipe Attack (Back Row)',
    category: 'Offense',
    tier: 'pro',
    description: 'Back-row player attacks through the middle from behind the attack line.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[260, 400], [320, 280]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[320, 280], [480, 300]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[250, 350], [400, 310]] },
      { type: 'circle', color: '#a3e635', lineWidth: 3, cx: 303, cy: 300, r: 25 },
    ],
    tokens: [
      { team: 'blue', label: '6', pct: [0.26, 0.67] },
      { team: 'blue', label: '2', pct: [0.32, 0.47] },
      { team: 'blue', label: '3', pct: [0.48, 0.43] },
      { team: 'blue', label: '4', pct: [0.16, 0.43] },
      { team: 'red',  label: '2', pct: [0.65, 0.47] },
      { team: 'red',  label: '3', pct: [0.75, 0.47] },
    ],
    phases: null,
  },
  {
    id: 'volleyball_blocking',
    sport: 'Volleyball',
    courtId: 'volleyball',
    name: 'Double Block Scheme',
    category: 'Defense',
    tier: 'pro',
    description: 'Two blockers close the angle on the opponent\'s main hitter; libero reads the line.',
    objects: [
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[820, 250], [620, 200]] },
      { type: 'rect', color: '#60a5fa', lineWidth: 3, x: 510, y: 130, w: 120, h: 60 },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[550, 190], [440, 400]] },
    ],
    tokens: [
      { team: 'blue', label: '2', pct: [0.55, 0.27] },
      { team: 'blue', label: '3', pct: [0.65, 0.27] },
      { team: 'blue', label: '5', pct: [0.16, 0.55] },
      { team: 'blue', label: '6', pct: [0.25, 0.65] },
      { team: 'red',  label: '4', pct: [0.82, 0.40] },
    ],
    phases: null,
  },
  {
    id: 'volleyball_serve_pattern',
    sport: 'Volleyball',
    courtId: 'volleyball',
    name: 'Jump Serve — Seam Attack',
    category: 'Serve',
    tier: 'pro',
    description: 'Target the seam between two receivers to force a miscommunication.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[200, 300], [660, 390]] },
      { type: 'circle', color: '#fbbf24', lineWidth: 3, cx: 660, cy: 390, r: 40 },
      { type: 'line', color: '#fbbf24', lineWidth: 2, points: [[640, 390], [700, 390]] },
    ],
    tokens: [
      { team: 'blue', label: '1', pct: [0.20, 0.50] },
      { team: 'red',  label: '6', pct: [0.65, 0.67] },
      { team: 'red',  label: '5', pct: [0.75, 0.60] },
    ],
    phases: null,
  },

  // ─────────────────────────────────────────────
  // HANDBALL (6 tactics)
  // Court: x=50–950, y=80–520
  // Goals at left x=50 and right x=950
  // Goal areas ~6m circle from goal
  // ─────────────────────────────────────────────
  {
    id: 'handball_7m_throw',
    sport: 'Handball',
    courtId: 'handball',
    name: '7-Metre Throw',
    category: 'Set Pieces',
    tier: 'free',
    description: 'Penalty throw; shooter reads goalkeeper movement to place the ball.',
    objects: [
      { type: 'circle', color: '#fbbf24', lineWidth: 3, cx: 230, cy: 300, r: 20 },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[230, 300], [70, 260]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[230, 300], [70, 340]] },
      { type: 'dashed-arrow', color: '#ef4444', lineWidth: 3, points: [[80, 300], [90, 260]] },
    ],
    tokens: [
      { team: 'blue', label: '10', pct: [0.23, 0.50] },
      { team: 'red',  label: 'GK', pct: [0.07, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'handball_fast_break',
    sport: 'Handball',
    courtId: 'handball',
    name: 'Fast Break',
    category: 'Offense',
    tier: 'free',
    description: 'Goalkeeper throws long to a wing player who breaks alone toward goal.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[80, 300], [550, 160]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[550, 160], [870, 200]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[870, 200], [920, 300]] },
    ],
    tokens: [
      { team: 'blue', label: 'GK', pct: [0.08, 0.50] },
      { team: 'blue', label: '9', pct: [0.55, 0.27] },
      { team: 'blue', label: '11', pct: [0.87, 0.33] },
      { team: 'red',  label: '4', pct: [0.50, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'handball_positional_attack',
    sport: 'Handball',
    courtId: 'handball',
    name: 'Positional Attack — Pivot Screen',
    category: 'Offense',
    tier: 'pro',
    description: 'Pivot screens a defender to free the playmaker for a penetrating pass.',
    objects: [
      { type: 'circle', color: '#fbbf24', lineWidth: 3, cx: 750, cy: 300, r: 35 },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[650, 300], [780, 270]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[780, 270], [860, 300]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[600, 200], [650, 300]] },
    ],
    tokens: [
      { team: 'blue', label: '10', pct: [0.65, 0.50] },
      { team: 'blue', label: '6', pct: [0.75, 0.50] },
      { team: 'blue', label: '9', pct: [0.60, 0.33] },
      { team: 'blue', label: '11', pct: [0.87, 0.40] },
      { team: 'red',  label: '4', pct: [0.68, 0.50] },
      { team: 'red',  label: '5', pct: [0.78, 0.43] },
    ],
    phases: null,
  },
  {
    id: 'handball_gk_positioning',
    sport: 'Handball',
    courtId: 'handball',
    name: 'Goalkeeper Positioning',
    category: 'Defense',
    tier: 'pro',
    description: 'Goalkeeper angles to cut the shooting angle based on ball position.',
    objects: [
      { type: 'line', color: '#fbbf24', lineWidth: 3, points: [[70, 300], [700, 220]] },
      { type: 'line', color: '#fbbf24', lineWidth: 3, points: [[70, 300], [700, 380]] },
      { type: 'circle', color: '#ef4444', lineWidth: 3, cx: 85, cy: 270, r: 22 },
      { type: 'arrow', color: '#ef4444', lineWidth: 3, points: [[85, 300], [85, 270]] },
    ],
    tokens: [
      { team: 'blue', label: 'GK', pct: [0.08, 0.50] },
      { team: 'red',  label: '10', pct: [0.70, 0.37] },
    ],
    phases: null,
  },
  {
    id: 'handball_6_0_defense',
    sport: 'Handball',
    courtId: 'handball',
    name: '6-0 Defensive Wall',
    category: 'Defense',
    tier: 'pro',
    description: 'Six defenders form a compact line across the 6-metre line to block all shots.',
    objects: [
      { type: 'line', color: '#60a5fa', lineWidth: 4, points: [[170, 230], [840, 230]] },
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[700, 200], [650, 230]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[700, 200], [840, 260]] },
    ],
    tokens: [
      { team: 'blue', label: '2', pct: [0.20, 0.38] },
      { team: 'blue', label: '3', pct: [0.34, 0.38] },
      { team: 'blue', label: '4', pct: [0.50, 0.38] },
      { team: 'blue', label: '5', pct: [0.66, 0.38] },
      { team: 'blue', label: '6', pct: [0.78, 0.38] },
      { team: 'blue', label: '7', pct: [0.86, 0.38] },
      { team: 'red',  label: '10', pct: [0.70, 0.33] },
    ],
    phases: null,
  },
  {
    id: 'handball_pivot_play',
    sport: 'Handball',
    courtId: 'handball',
    name: 'Pivot Play — Circle Entry',
    category: 'Offense',
    tier: 'pro',
    description: 'Backcourt player passes into the pivot who turns and shoots or lays off.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[680, 220], [820, 300]] },
      { type: 'circle', color: '#fbbf24', lineWidth: 3, cx: 820, cy: 300, r: 30 },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[820, 300], [900, 300]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[820, 300], [860, 240]] },
    ],
    tokens: [
      { team: 'blue', label: '10', pct: [0.68, 0.37] },
      { team: 'blue', label: '6', pct: [0.82, 0.50] },
      { team: 'blue', label: '9', pct: [0.87, 0.40] },
      { team: 'red',  label: '4', pct: [0.80, 0.43] },
      { team: 'red',  label: '5', pct: [0.78, 0.57] },
    ],
    phases: null,
  },

  // ─────────────────────────────────────────────
  // RUGBY (6 tactics)
  // Pitch: x=50–950, y=50–550
  // Try lines at x=50 and x=950; 22m ~x=206 and x=794
  // ─────────────────────────────────────────────
  {
    id: 'rugby_lineout',
    sport: 'Rugby',
    courtId: 'rugby_union',
    name: 'Lineout — Peel Move',
    category: 'Set Pieces',
    tier: 'free',
    description: 'Throw to the back of the lineout and peel around for a quick drive.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[580, 100], [580, 280]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[580, 280], [500, 350]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[500, 350], [420, 350]] },
    ],
    tokens: [
      { team: 'blue', label: '2', pct: [0.58, 0.10] },
      { team: 'blue', label: '4', pct: [0.58, 0.30] },
      { team: 'blue', label: '5', pct: [0.58, 0.40] },
      { team: 'blue', label: '6', pct: [0.58, 0.47] },
      { team: 'blue', label: '9', pct: [0.50, 0.58] },
      { team: 'red',  label: '4', pct: [0.62, 0.30] },
    ],
    phases: null,
  },
  {
    id: 'rugby_scrum',
    sport: 'Rugby',
    courtId: 'rugby_union',
    name: 'Scrum — Blind-Side Crash',
    category: 'Set Pieces',
    tier: 'free',
    description: 'Pick from the back of the scrum and crash the blind-side flank.',
    objects: [
      { type: 'rect', color: '#60a5fa', lineWidth: 2, x: 480, y: 240, w: 80, h: 120 },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[540, 300], [450, 300]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[450, 300], [350, 280]] },
    ],
    tokens: [
      { team: 'blue', label: '8', pct: [0.54, 0.50] },
      { team: 'blue', label: '9', pct: [0.45, 0.50] },
      { team: 'blue', label: '6', pct: [0.35, 0.47] },
      { team: 'red',  label: '7', pct: [0.52, 0.43] },
    ],
    phases: null,
  },
  {
    id: 'rugby_maul',
    sport: 'Rugby',
    courtId: 'rugby_union',
    name: 'Driving Maul',
    category: 'Offense',
    tier: 'pro',
    description: 'Build a driving maul from a lineout to power over the try line.',
    objects: [
      { type: 'rect', color: '#60a5fa', lineWidth: 3, x: 300, y: 260, w: 80, h: 80 },
      { type: 'arrow', color: '#60a5fa', lineWidth: 5, points: [[300, 300], [100, 300]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[340, 250], [340, 260]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[340, 350], [340, 340]] },
    ],
    tokens: [
      { team: 'blue', label: '4', pct: [0.34, 0.43] },
      { team: 'blue', label: '5', pct: [0.34, 0.57] },
      { team: 'blue', label: '6', pct: [0.34, 0.50] },
      { team: 'blue', label: '8', pct: [0.28, 0.50] },
      { team: 'red',  label: '4', pct: [0.30, 0.43] },
      { team: 'red',  label: '5', pct: [0.30, 0.57] },
    ],
    phases: null,
  },
  {
    id: 'rugby_line_break',
    sport: 'Rugby',
    courtId: 'rugby_union',
    name: 'Line Break — Offload',
    category: 'Offense',
    tier: 'pro',
    description: 'Carrier breaks the defensive line and offloads to a supporting runner.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[430, 300], [620, 300]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[620, 300], [720, 260]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[720, 260], [850, 250]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[430, 350], [620, 310]] },
    ],
    tokens: [
      { team: 'blue', label: '12', pct: [0.43, 0.50] },
      { team: 'blue', label: '13', pct: [0.72, 0.43] },
      { team: 'blue', label: '14', pct: [0.85, 0.42] },
      { team: 'red',  label: '13', pct: [0.58, 0.50] },
      { team: 'red',  label: '12', pct: [0.50, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'rugby_blindside_attack',
    sport: 'Rugby',
    courtId: 'rugby_union',
    name: 'Blind-Side Attack',
    category: 'Offense',
    tier: 'pro',
    description: 'Exploit the narrow side with a quick ruck recycle and crash ball.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[500, 300], [550, 200]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[550, 200], [650, 200]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[500, 300], [480, 200]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[480, 200], [380, 180]] },
    ],
    tokens: [
      { team: 'blue', label: '9', pct: [0.50, 0.50] },
      { team: 'blue', label: '8', pct: [0.55, 0.33] },
      { team: 'blue', label: '6', pct: [0.48, 0.33] },
      { team: 'blue', label: '7', pct: [0.38, 0.30] },
      { team: 'red',  label: '7', pct: [0.52, 0.40] },
    ],
    phases: null,
  },
  {
    id: 'rugby_kick_chase',
    sport: 'Rugby',
    courtId: 'rugby_union',
    name: 'Kick & Chase',
    category: 'Offense',
    tier: 'pro',
    description: 'Kick deep into territory and chase hard to pressure the receiver.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[430, 300], [850, 200]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[430, 300], [650, 270]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[430, 320], [700, 290]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[430, 340], [750, 310]] },
      { type: 'circle', color: '#ef4444', lineWidth: 3, cx: 850, cy: 200, r: 40 },
    ],
    tokens: [
      { team: 'blue', label: '10', pct: [0.43, 0.50] },
      { team: 'blue', label: '6', pct: [0.65, 0.45] },
      { team: 'blue', label: '7', pct: [0.70, 0.48] },
      { team: 'blue', label: '8', pct: [0.75, 0.52] },
      { team: 'red',  label: '15', pct: [0.85, 0.33] },
    ],
    phases: null,
  },

  // ─────────────────────────────────────────────
  // AMERICAN FOOTBALL (8 tactics)
  // Field: x=50–950, y=70–530
  // End zones at each end; center of field y=300
  // ─────────────────────────────────────────────
  {
    id: 'amfootball_shotgun',
    sport: 'American Football',
    courtId: 'american_football',
    name: 'Shotgun Formation',
    category: 'Offense',
    tier: 'free',
    description: 'QB lines up in shotgun; WRs split wide with a slot receiver in the middle.',
    objects: [
      { type: 'line', color: '#fbbf24', lineWidth: 3, points: [[500, 300], [500, 280]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[300, 300], [200, 200]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[700, 300], [800, 200]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[400, 310], [380, 200]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[600, 310], [620, 200]] },
    ],
    tokens: [
      { team: 'blue', label: 'QB', pct: [0.50, 0.52] },
      { team: 'blue', label: 'C', pct:  [0.50, 0.47] },
      { team: 'blue', label: 'LG', pct: [0.46, 0.47] },
      { team: 'blue', label: 'RG', pct: [0.54, 0.47] },
      { team: 'blue', label: 'WR', pct: [0.30, 0.50] },
      { team: 'blue', label: 'WR', pct: [0.70, 0.50] },
      { team: 'blue', label: 'SL', pct: [0.40, 0.52] },
      { team: 'blue', label: 'RB', pct: [0.60, 0.52] },
    ],
    phases: null,
  },
  {
    id: 'amfootball_blitz',
    sport: 'American Football',
    courtId: 'american_football',
    name: 'Blitz Package',
    category: 'Defense',
    tier: 'free',
    description: 'Send extra rushers to overwhelm the offensive line and pressure the QB.',
    objects: [
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[450, 380], [490, 310]] },
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[550, 380], [510, 310]] },
      { type: 'arrow', color: '#ef4444', lineWidth: 4, points: [[380, 360], [470, 310]] },
      { type: 'circle', color: '#ef4444', lineWidth: 3, cx: 500, cy: 300, r: 50 },
    ],
    tokens: [
      { team: 'red',  label: 'SS', pct: [0.45, 0.63] },
      { team: 'red',  label: 'FS', pct: [0.55, 0.63] },
      { team: 'red',  label: 'LB', pct: [0.38, 0.60] },
      { team: 'red',  label: 'CB', pct: [0.30, 0.50] },
      { team: 'red',  label: 'CB', pct: [0.70, 0.50] },
      { team: 'blue', label: 'QB', pct: [0.50, 0.48] },
    ],
    phases: null,
  },
  {
    id: 'amfootball_zone_coverage',
    sport: 'American Football',
    courtId: 'american_football',
    name: 'Cover 2 Zone',
    category: 'Defense',
    tier: 'pro',
    description: 'Two safeties split the deep field; cornerbacks take the flats.',
    objects: [
      { type: 'rect', color: '#ef4444', lineWidth: 2, x: 50, y: 70, w: 430, h: 200 },
      { type: 'rect', color: '#ef4444', lineWidth: 2, x: 480, y: 70, w: 420, h: 200 },
      { type: 'rect', color: '#60a5fa', lineWidth: 2, x: 50, y: 270, w: 200, h: 120 },
      { type: 'rect', color: '#60a5fa', lineWidth: 2, x: 700, y: 270, w: 200, h: 120 },
    ],
    tokens: [
      { team: 'red',  label: 'SS', pct: [0.30, 0.25] },
      { team: 'red',  label: 'FS', pct: [0.70, 0.25] },
      { team: 'red',  label: 'CB', pct: [0.16, 0.52] },
      { team: 'red',  label: 'CB', pct: [0.84, 0.52] },
      { team: 'red',  label: 'LB', pct: [0.40, 0.52] },
      { team: 'red',  label: 'LB', pct: [0.60, 0.52] },
    ],
    phases: null,
  },
  {
    id: 'amfootball_hail_mary',
    sport: 'American Football',
    courtId: 'american_football',
    name: 'Hail Mary',
    category: 'Set Pieces',
    tier: 'pro',
    description: 'Long bomb to the end zone with multiple receivers for the desperation touchdown.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 5, points: [[250, 300], [900, 300]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 3, points: [[250, 300], [900, 220]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 3, points: [[250, 300], [900, 380]] },
      { type: 'circle', color: '#a3e635', lineWidth: 3, cx: 900, cy: 300, r: 60 },
    ],
    tokens: [
      { team: 'blue', label: 'QB', pct: [0.25, 0.50] },
      { team: 'blue', label: 'WR', pct: [0.90, 0.37] },
      { team: 'blue', label: 'WR', pct: [0.90, 0.50] },
      { team: 'blue', label: 'WR', pct: [0.90, 0.63] },
      { team: 'red',  label: 'CB', pct: [0.88, 0.35] },
      { team: 'red',  label: 'SS', pct: [0.88, 0.53] },
    ],
    phases: null,
  },
  {
    id: 'amfootball_screen_pass',
    sport: 'American Football',
    courtId: 'american_football',
    name: 'Screen Pass',
    category: 'Offense',
    tier: 'pro',
    description: 'Draw the pass rush in, then flip it to the RB behind blockers in the flat.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[400, 300], [300, 350]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[330, 310], [250, 310]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[370, 310], [300, 310]] },
      { type: 'dashed-arrow', color: '#fbbf24', lineWidth: 3, points: [[300, 350], [200, 300]] },
    ],
    tokens: [
      { team: 'blue', label: 'QB', pct: [0.40, 0.50] },
      { team: 'blue', label: 'RB', pct: [0.30, 0.58] },
      { team: 'blue', label: 'LT', pct: [0.33, 0.52] },
      { team: 'blue', label: 'LG', pct: [0.37, 0.52] },
      { team: 'red',  label: 'DE', pct: [0.43, 0.50] },
    ],
    phases: null,
  },
  {
    id: 'amfootball_qb_sneak',
    sport: 'American Football',
    courtId: 'american_football',
    name: 'QB Sneak',
    category: 'Offense',
    tier: 'pro',
    description: 'QB takes a direct snap and dives straight ahead behind the center.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 5, points: [[500, 310], [540, 310]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[460, 310], [460, 300]] },
      { type: 'arrow', color: '#60a5fa', lineWidth: 3, points: [[540, 310], [540, 300]] },
    ],
    tokens: [
      { team: 'blue', label: 'QB', pct: [0.50, 0.53] },
      { team: 'blue', label: 'C', pct:  [0.50, 0.47] },
      { team: 'blue', label: 'LG', pct: [0.46, 0.47] },
      { team: 'blue', label: 'RG', pct: [0.54, 0.47] },
      { team: 'red',  label: 'NT', pct: [0.50, 0.43] },
    ],
    phases: null,
  },
  {
    id: 'amfootball_redzone',
    sport: 'American Football',
    courtId: 'american_football',
    name: 'Red Zone — Corner Route',
    category: 'Offense',
    tier: 'pro',
    description: 'Quick corner route to the back of the end zone against man coverage.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 4, points: [[750, 300], [800, 220]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 4, points: [[800, 220], [880, 120]] },
      { type: 'dashed-arrow', color: '#60a5fa', lineWidth: 3, points: [[650, 330], [800, 220]] },
    ],
    tokens: [
      { team: 'blue', label: 'QB', pct: [0.65, 0.55] },
      { team: 'blue', label: 'WR', pct: [0.75, 0.50] },
      { team: 'blue', label: 'TE', pct: [0.68, 0.47] },
      { team: 'red',  label: 'CB', pct: [0.77, 0.48] },
      { team: 'red',  label: 'SS', pct: [0.80, 0.35] },
    ],
    phases: null,
  },
  {
    id: 'amfootball_kickoff_return',
    sport: 'American Football',
    courtId: 'american_football',
    name: 'Kickoff Return — Middle',
    category: 'Set Pieces',
    tier: 'pro',
    description: 'Wedge blockers create a lane up the middle for the returner.',
    objects: [
      { type: 'arrow', color: '#60a5fa', lineWidth: 5, points: [[500, 450], [500, 250]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 3, points: [[420, 380], [440, 340]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 3, points: [[470, 380], [480, 340]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 3, points: [[530, 380], [520, 340]] },
      { type: 'arrow', color: '#fbbf24', lineWidth: 3, points: [[580, 380], [560, 340]] },
    ],
    tokens: [
      { team: 'blue', label: 'KR', pct: [0.50, 0.75] },
      { team: 'blue', label: 'G1', pct: [0.42, 0.63] },
      { team: 'blue', label: 'G2', pct: [0.47, 0.63] },
      { team: 'blue', label: 'G3', pct: [0.53, 0.63] },
      { team: 'blue', label: 'G4', pct: [0.58, 0.63] },
      { team: 'red',  label: '1', pct: [0.40, 0.47] },
      { team: 'red',  label: '2', pct: [0.60, 0.47] },
    ],
    phases: null,
  },

];
